# Parameters for apriltag detector node
family: "tag36h11"
nthreads: 3
quad_decimate: 4.0
quad_sigma: 0.0
refine_edges: 1
decode_sharpening: 0.25
tag_size: 0.065

# Set the number of paralell processes
number_of_cores: 4
# Parameters for dividing the Apriltagnode into smaller frames
regions_of_interest:  
 -  x_offset: 0
    y_offset: 0
    height: 52
    width: 52
 -  x_offset: 48
    y_offset: 0
    height: 52
    width: 52
 -  x_offset: 0
    y_offset: 52
    height: 52
    width: 52
 -  x_offset: 48
    y_offset: 52
    height: 52
    width: 52

